cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2024.12.1
  ai_chat_mode: none
  ai_image_mode: none
  author_name: Ibrahim
  ci: none
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: The most amazing SaaS application the world has ever seen
  docker_setup: default
  domain_name: localhost:8000
  email: ibrahimshaban1994@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: Fadiybrahim
  include_static_files: n
  marketing_email_platform: none
  post_process: n
  project_name: Basic
  project_slug: basic
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_auth: n
  use_api_keys: n
  use_async_example: n
  use_cloud_media_storage: n
  use_dark_mode: n
  use_debug_toolbar: n
  use_docker: n
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: n
  use_impersonation: n
  use_sentry: n
  use_shadcn: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: n
  use_wagtail: n
